#!/usr/bin/env php
<?php

if (file_exists($autoload = __DIR__ . '/vendor/autoload.php')) {
    require $autoload;
} else {
    require dirname(__DIR__, 2) . '/autoload.php';
}

$application = new \Symfony\Component\Console\Application();
$application->add(new \Webteractive\EE\GenerateCommand);
$application->add(new \Webteractive\EE\MakeServiceCommand);
$application->run();