#!/usr/bin/env php
<?php

if (file_exists($autoload = __DIR__ . '/vendor/autoload.php')) {
    require $autoload;
} else {
    require dirname(__DIR__, 2) . '/autoload.php';
}

use Webteractive\EE\GenerateCommand;
use Webteractive\EE\MakeServiceCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new GenerateCommand);
$application->add(new MakeServiceCommand);

$application->run();